[package]
name = "dynhost"
version = "0.1.0"
authors = ["William Durand <will+git@drnd.me>"]
edition = "2018"

[dependencies]
reqwest = "0.9.10"

[dev-dependencies]
env_logger = { version = "0.6.0", default-features = false }
mockito = "0.16.0"
