[package]
name = "dynhost"
version = "0.1.0"
authors = ["William Durand <will+git@drnd.me>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.12.24", features = ["blocking"] }

[dev-dependencies]
env_logger = { version = "0.11.8", default-features = false }
mockito = "0.16.0"
